/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.casa.chaptercreator;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class ChapterCreator extends javax.swing.JFrame {

    /**
     * Creates new form ChapterCreator
     */
    public ChapterCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaChapters = new javax.swing.JTextArea();
        jButtonGenerate = new javax.swing.JButton();
        jLabelFileName = new javax.swing.JLabel();
        jTextFileName = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jTextAreaChapters.setColumns(20);
        jTextAreaChapters.setRows(5);
        jScrollPane1.setViewportView(jTextAreaChapters);

        jButtonGenerate.setText("Generate");
        jButtonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateActionPerformed(evt);
            }
        });

        jLabelFileName.setText("File Name:");

        jTextFileName.setToolTipText("Enter File Name...");
        jTextFileName.setName(""); // NOI18N

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ChapterCreator");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("by Carlos Martinez");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelFileName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFileName))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jButtonGenerate)
                                .addGap(58, 58, 58)
                                .addComponent(jButtonClear))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(jLabel2)))
                        .addGap(0, 205, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFileName)
                    .addComponent(jTextFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerate)
                    .addComponent(jButtonClear))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateActionPerformed
        String rawchapters=jTextAreaChapters.getText();
        String filename=jTextFileName.getText();
        String txtstamp="";
        String texthours="";
        String textminutes="";
        String textseconds="";
        int hours=0;
        int minutes=0;
        int seconds=0;
        int preminutes=0;
        int preseconds=0;
        String[] ptstamp;
        ArrayList<String> chapterout = new ArrayList<>();
        String[] chapters=rawchapters.split("\\n");
        JFrame frame = new JFrame("JOptionPane showMessageDialog example");

        if(filename.equals("")){
            JOptionPane.showMessageDialog(frame, "Insert a File Name");
        }else if(rawchapters.equals("")){
            JOptionPane.showMessageDialog(frame, "Insert Chapters");
        }else{
            for (int i = 0; i < chapters.length; i++) {
                if (i==0){
                    txtstamp=(chapters[i].substring(chapters[i].indexOf("[")+1,chapters[i].indexOf("]")));
                    ptstamp=txtstamp.split(":");
                    if (ptstamp[0].equals("")){
                        preminutes=0;
                    }else{
                        preminutes=Integer.valueOf(ptstamp[0]);
                    }
                    preseconds=Integer.valueOf(ptstamp[1]);
                    chapterout.add("CHAPTER0" + (i+1) + "=00:00:00.000");
                    chapterout.add("CHAPTER0" + (i+1) + "NAME=" + (chapters[i].substring(3,chapters[i].indexOf("[")-1)));
                }else if (i<9){
                    seconds=seconds+preseconds;
                    minutes=minutes+preminutes;
                    if(seconds>=60){
                        minutes++;
                        seconds=seconds-60;
                    }
                    if (minutes>=60){
                        hours++;
                        minutes=minutes-60;
                    }
                    texthours=String.format("%02d", hours);
                    textminutes=String.format("%02d", minutes);
                    textseconds=String.format("%02d", seconds);
                    chapterout.add("CHAPTER0" + (i+1) + "=" + texthours + ":" + textminutes + ":" + textseconds + ".000");
                    chapterout.add("CHAPTER0" + (i+1) + "NAME=" + (chapters[i].substring(3,chapters[i].indexOf("[")-1)));
                    txtstamp=(chapters[i].substring(chapters[i].indexOf("[")+1,chapters[i].indexOf("]")));
                    ptstamp=txtstamp.split(":");
                    if (ptstamp[0].equals("")){
                        preminutes=0;
                    }else{
                        preminutes=Integer.valueOf(ptstamp[0]);
                    }
                    preseconds=Integer.valueOf(ptstamp[1]);
                }else if (i>=9){
                    seconds=seconds+preseconds;
                    minutes=minutes+preminutes;
                    if(seconds>=60){
                        minutes++;
                        seconds=seconds-60;
                    }
                    if (minutes>=60){
                        hours++;
                        minutes=minutes-60;
                    }
                    texthours=String.format("%02d", hours);
                    textminutes=String.format("%02d", minutes);
                    textseconds=String.format("%02d", seconds);

                    chapterout.add("CHAPTER" + (i+1) + "=" + texthours + ":" + textminutes + ":" + textseconds + ".000");
                    chapterout.add("CHAPTER" + (i+1) + "NAME=" + (chapters[i].substring(4,chapters[i].indexOf("[")-1)));
                    txtstamp=(chapters[i].substring(chapters[i].indexOf("[")+1,chapters[i].indexOf("]")));
                    ptstamp=txtstamp.split(":");    
                    if (ptstamp[0].equals("")){
                        preminutes=0;
                    }else{
                        preminutes=Integer.valueOf(ptstamp[0]);    
                    }
                    preseconds=Integer.valueOf(ptstamp[1]);
                }
            }
            try (PrintStream out = new PrintStream(new FileOutputStream(filename + ".txt"))) {
                for (String j : chapterout) {
                    out.print(j);
                    out.print("\n");
                }
                System.out.println("success");
                JOptionPane.showMessageDialog(frame, "Chapter File Created Successfully!");
            }catch (FileNotFoundException ex) {
                Logger.getLogger(ChapterCreator.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
        
                    

    }//GEN-LAST:event_jButtonGenerateActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextAreaChapters.setText(null);
        jTextFileName.setText(null);
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChapterCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChapterCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChapterCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChapterCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChapterCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFileName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaChapters;
    private javax.swing.JTextField jTextFileName;
    // End of variables declaration//GEN-END:variables
}
